import argparse
import os
from dotenv import load_dotenv
load_dotenv()

import torch

parser = argparse.ArgumentParser("mean_influence")


parser.add_argument("in_path", help="The filepath generated by process_gradiens.py")
parser.add_argument("out_path")
args = parser.parse_args()



output_dir = os.path.dirname(args.out_path)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
t = torch.load(args.in_path,weights_only=True,map_location="cpu").to(dtype=torch.float64)
torch.save(t.mean(axis=1), args.out_path)
